### ISSUE TITLE
Data don't apply on notification in IOS Devices

### ISSUE THREAD

**Issue by shaharhn** [rafaelsetragni/awesome_notifications_fcm#38]
I have a server with handles there all the notifications.

I've tried to make a notification with actions and image as we have in the local in the example.

Results:
Android: works perfectly, locally notifications and remote notifications received with all the parameters include image and actions.
IOS: partly works, locally notifications works perfectly, remote notifications doesn't receive any of the data, not actions and not image.

For this try I used your example in backend like as the flutter example.

https://github.com/rafaelsetragni/awesome_notifications_fcm/tree/main/example

**Comment by rafaelsetragni** [comment]
Im sorry, but there is a ton of information skipped because you had not set the previous form with key informations that i need now. So i have no idea of how you implemented your app.

The only thing that i can suggest is you to remember to not use concurrent notification plugins, such as flutter_local_notifications or firebase_messaging, because they will compete to get native resources and many side effects can happen because of it.

**Comment by shaharhn** [comment]
@rafaelsetragni Thanks for the fast response, I don't use any other plugins, I'm trying to make the example working but it still looks the same, the local notifications work perfect with the buttons but when I send it from my server it looks like it doesn't handle all the things under 'data'.

Do you have any idea why ?
